name: Rust build&test Check

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    services:
      postgres:
        image: postgres
        # refer: https://hub.docker.com/_/postgres
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin
          POSTGRES_DB: test_db
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 4321:5432

    steps:
    - uses: actions/checkout@v4
    - name: Install sqlx-cli
      run: cargo install --version=0.8.0 sqlx-cli --no-default-features --features postgres
    - name: Set up PostgreSQL
      env:
        DATABASE_URL: postgresql://admin:admin@localhost:4321/test_db
      run: |
        sqlx db create
        sqlx migrate run
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        DATABASE_URL: postgresql://admin:admin@localhost:4321/test_db
      run: cargo test --verbose
