name: Rust build&test Check

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd backend
        cargo build --verbose
    - name: Run tests
      run: |
        cd backend
        cargo test --verbose
